# Generated by Django 3.2.5 on 2021-07-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='talla',
        ),
    ]
